using DesignPrinciplesCSharp.Solid.DependencyInversionPrinciple;
using DesignPrinciplesCSharp.Solid.InterfaceSegregationPrinciple;
using DesignPrinciplesCSharp.Solid.LiskovSubstitutionPrinciple;
using DesignPrinciplesCSharp.Solid.OpenClosedPrinciple;
using DesignPrinciplesCSharp.Solid.SingleResponsibilityPrinciple;

SingleResponsibilityPrinciple.Execute();
OpenClosedPrinciple.Execute();
LiskovSubstitutionPrinciple.Execute();
InterfaceSegregationPrinciple.Execute();
DependencyInversionPrinciple.Execute();